### ISSUE TITLE
Please provide license!

### ISSUE THREAD

**Issue by raiscan** [daviscook477/kparser#4]
Hi!

I'd like to use part of this project for my own (Java-based Oxygen Not Included animated graphics exporter, for the purpose of documenting beta graphics, changes etc.) but, unless I'm missing something, your project has no software license and thus I can't presume you allow derivative work.

Could you please provide license to your source or permit derivative works in some way? Thank you!

**Comment by daviscook477** [comment]
Hey thanks for the feedback. Let me resolve this for you

**Comment by daviscook477** [comment]
Also you might want to take a look at KSE by skairunner in the ONI modding discord. It's an improved version of this conversion tool that's written in C#

**Comment by daviscook477** [comment]
I'm not going to make a new release but I've attached a license to the master branch

**Comment by raiscan** [comment]
Thanks for your enterprise-level response time and contribution :)
